version: 0.2

phases:
  install:
    commands:
      - echo Installing httpd
      - sudo yum install httpd  -y
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuration NGINX

artifacts:
  files:
    - '**/*'


